// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:4ffe52b6-13ea-44db-ac24-b72f41f0a98d',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_M4hM9tigD',
  aws_user_pools_web_client_id: '4l2b7eg5hh5dtm9umv3896i8t3',
  oauth: {},
  aws_user_files_s3_bucket: 's3kumulus11247-demo',
  aws_user_files_s3_bucket_region: 'us-east-1',
  aws_appsync_graphqlEndpoint: 'https://2dtgxi2cjrgdbcqu5wvbbmu3ee.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AWS_IAM',
  aws_content_delivery_bucket: 'kumulus-20200107043357-hostingbucket-demo',
  aws_content_delivery_bucket_region: 'us-east-1',
  aws_content_delivery_url: 'https://d3i0ccflh15a8n.cloudfront.net',
};

export default awsmobile;
